# Generated by Django 6.0.3 on 2026-04-29 20:03

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ol_id', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('titre', models.CharField(max_length=300)),
                ('auteur', models.CharField(blank=True, max_length=200, null=True)),
                ('genre', models.CharField(blank=True, max_length=100, null=True)),
                ('sous_genre', models.CharField(blank=True, max_length=100, null=True)),
                ('annee', models.IntegerField(blank=True, null=True)),
                ('nb_pages', models.IntegerField(blank=True, null=True)),
                ('langue', models.CharField(default='fr', max_length=10)),
                ('categorie_age', models.CharField(choices=[('enfant', 'Enfant'), ('ado', 'Ado'), ('adulte', 'Adulte')], default='adulte', max_length=10)),
                ('mots_cles', models.JSONField(blank=True, null=True)),
                ('note_moyenne', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('nb_notes', models.IntegerField(default=0)),
                ('nb_emprunts', models.IntegerField(default=0)),
                ('popularite', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('vecteur_livre', models.JSONField(blank=True, null=True)),
                ('disponible', models.BooleanField(default=True)),
                ('resume', models.TextField(blank=True, null=True)),
                ('couverture_url', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('type_compte', models.CharField(choices=[('anonyme', 'Anonyme'), ('non_membre', 'Non-membre'), ('membre', 'Membre')], default='non_membre', max_length=20)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('niveau_etude', models.CharField(blank=True, choices=[('école', 'École'), ('lycée', 'Lycée'), ('étudiant', 'Étudiant'), ('professionnel', 'Professionnel'), ('autre', 'Autre')], max_length=20, null=True)),
                ('classe', models.CharField(blank=True, max_length=50, null=True)),
                ('genre_prefere', models.CharField(blank=True, max_length=100, null=True)),
                ('sous_genre_prefere', models.CharField(blank=True, max_length=100, null=True)),
                ('score_confiance', models.DecimalField(decimal_places=3, default=0.0, max_digits=4)),
                ('profil_complet', models.BooleanField(default=False)),
                ('vecteur_profil', models.JSONField(blank=True, null=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('date_emprunt', models.DateField()),
                ('date_prevue', models.DateField()),
                ('date_retour', models.DateField(blank=True, null=True)),
                ('renouvele', models.BooleanField(default=False)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('rendu', 'Rendu'), ('perdu', 'Perdu')], default='en_cours', max_length=20)),
                ('poids', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrows', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('type_action', models.CharField(choices=[('vue', 'Vue'), ('note', 'Note'), ('like', 'Like'), ('chat_ia', 'Chat IA'), ('marquage', 'Marquage')], max_length=20)),
                ('notation', models.IntegerField(blank=True, null=True)),
                ('duree_secondes', models.IntegerField(blank=True, null=True)),
                ('livre_lu', models.BooleanField(default=False)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('source', models.CharField(choices=[('application', 'Application'), ('chat_ia', 'Chat IA'), ('recherche', 'Recherche')], default='application', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('type_notif', models.CharField(choices=[('rappel_retour', 'Rappel retour'), ('retard', 'Retard'), ('livre_disponible', 'Livre disponible'), ('nouvelle_recommandation', 'Nouvelle recommandation')], max_length=30)),
                ('message', models.TextField()),
                ('envoyee_le', models.DateTimeField(auto_now_add=True)),
                ('lue', models.BooleanField(default=False)),
                ('emprunt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.borrow')),
                ('livre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SessionIA',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('humeur_detectee', models.CharField(choices=[('léger', 'Léger'), ('intense', 'Intense'), ('évasion', 'Évasion'), ('neutre', 'Neutre'), ('triste', 'Triste'), ('aventurier', 'Aventurier'), ('romantique', 'Romantique'), ('curieux', 'Curieux'), ('nostalgique', 'Nostalgique'), ('stressé', 'Stressé'), ('détendu', 'Détendu')], default='neutre', max_length=20)),
                ('vecteur_intention', models.JSONField(blank=True, null=True)),
                ('livres_rejetes', models.JSONField(blank=True, null=True)),
                ('livres_acceptes', models.JSONField(blank=True, null=True)),
                ('debut', models.DateTimeField(auto_now_add=True)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SimilarBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=4, max_digits=5)),
                ('date_calcul', models.DateTimeField(auto_now_add=True)),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarities_from', to='api.book')),
                ('similaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarities_to', to='api.book')),
            ],
            options={
                'unique_together': {('livre', 'similaire')},
            },
        ),
    ]
