# Generated by Django 6.0.3 on 2026-04-08 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='books_read',
        ),
        migrations.RemoveField(
            model_name='user',
            name='clubs_joined',
        ),
        migrations.RemoveField(
            model_name='user',
            name='events_attended',
        ),
        migrations.RemoveField(
            model_name='user',
            name='level',
        ),
        migrations.RemoveField(
            model_name='user',
            name='reviews_posted',
        ),
        migrations.RemoveField(
            model_name='user',
            name='xp',
        ),
    ]
