# Generated by Django 6.0.4 on 2026-04-29 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('excerpt', models.TextField()),
                ('content', models.TextField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=300, null=True)),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('announcement', 'Annonce'), ('event', 'Événement'), ('course', 'Cours'), ('visit', 'Visite'), ('closure', 'Fermeture'), ('general', 'Général')], default='general', max_length=20)),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ReadingClub',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.CharField(blank=True, max_length=300, null=True)),
                ('target_audience', models.CharField(choices=[('children', 'Children'), ('teen', 'Teen'), ('adult', 'Adult'), ('all', 'All')], default='all', max_length=20)),
                ('member_count', models.IntegerField(default=0)),
                ('manager_name', models.CharField(blank=True, max_length=100, null=True)),
                ('manager_role', models.CharField(blank=True, max_length=100, null=True)),
                ('manager_email', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('users', models.ManyToManyField(related_name='user_badges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type_event', models.CharField(choices=[('club', 'Club'), ('conference', 'Conférence'), ('workshop', 'Atelier')], default='conference', max_length=20)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=200)),
                ('participant_count', models.IntegerField(default=0)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.readingclub')),
            ],
        ),
    ]
