# Generated by Django 6.0.4 on 2026-04-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_news_readingclub_badge_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='xp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='type_action',
            field=models.CharField(choices=[('vue', 'Vue'), ('note', 'Note'), ('like', "J'aime"), ('chat_ia', 'Chat IA'), ('marquage', 'Marquage')], max_length=20),
        ),
        migrations.AlterField(
            model_name='readingclub',
            name='target_audience',
            field=models.CharField(choices=[('children', 'Enfants'), ('teen', 'Adolescents'), ('adult', 'Adultes'), ('all', 'Tout public')], default='all', max_length=20),
        ),
    ]
