# Generated by Django 6.0.4 on 2026-05-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_labstation_labreservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type_compte',
            field=models.CharField(choices=[('anonyme', 'Anonyme'), ('non_membre', 'Non-membre'), ('en_attente', 'En attente'), ('membre', 'Membre')], default='non_membre', max_length=20),
        ),
    ]
