# Generated by Django 6.0.4 on 2026-04-30 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_reservation_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='level',
        ),
        migrations.RemoveField(
            model_name='user',
            name='xp',
        ),
        migrations.DeleteModel(
            name='Badge',
        ),
    ]
