# Generated by Django 6.0.4 on 2026-05-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_telephone_participationevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type_notif',
            field=models.CharField(choices=[('rappel_retour', 'Rappel retour'), ('retard', 'Retard'), ('livre_disponible', 'Livre disponible'), ('demande_adhesion', 'Demande adhésion'), ('adhesion_confirmee', 'Adhésion confirmée'), ('inscription_evenement', 'Inscription événement')], max_length=30),
        ),
    ]
