# Generated by Django 6.0.4 on 2026-05-13 13:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_notification_type_notif'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingclub',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='clubs_adherant', to=settings.AUTH_USER_MODEL),
        ),
    ]
