# Generated by Django 6.0.4 on 2026-04-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_favorites_user_intentions_alter_user_classe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='mots_cles',
        ),
        migrations.RemoveField(
            model_name='book',
            name='nb_emprunts',
        ),
        migrations.RemoveField(
            model_name='book',
            name='popularite',
        ),
        migrations.RemoveField(
            model_name='book',
            name='vecteur_livre',
        ),
        migrations.RemoveField(
            model_name='borrow',
            name='poids',
        ),
        migrations.RemoveField(
            model_name='user',
            name='genre_prefere',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profil_complet',
        ),
        migrations.RemoveField(
            model_name='user',
            name='score_confiance',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sous_genre_prefere',
        ),
        migrations.RemoveField(
            model_name='user',
            name='vecteur_profil',
        ),
        migrations.AlterField(
            model_name='notification',
            name='type_notif',
            field=models.CharField(choices=[('rappel_retour', 'Rappel retour'), ('retard', 'Retard'), ('livre_disponible', 'Livre disponible')], max_length=30),
        ),
        migrations.DeleteModel(
            name='SimilarBook',
        ),
    ]
