# Generated by Django 6.0.4 on 2026-05-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_book_mots_cles_localisation_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='codes_barres',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
