# Generated by Django 6.0.5 on 2026-05-27 03:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_book_codes_barres_alter_book_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labreservation',
            name='station',
        ),
        migrations.RemoveField(
            model_name='labreservation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='book',
            name='ol_id',
        ),
        migrations.RemoveField(
            model_name='borrow',
            name='date_emprunt',
        ),
        migrations.RemoveField(
            model_name='borrow',
            name='date_prevue',
        ),
        migrations.RemoveField(
            model_name='borrow',
            name='date_retour',
        ),
        migrations.AddField(
            model_name='book',
            name='cote',
            field=models.CharField(blank=True, help_text='Cote physique de rangement (texte libre, ex: R-042).', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, help_text="Description littéraire ou technique additionnelle pour l'IA.", null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='duree_emprunt_moy',
            field=models.FloatField(default=0.0, help_text="Durée moyenne d'emprunt en jours sur l'ensemble des retours."),
        ),
        migrations.AddField(
            model_name='book',
            name='nb_emprunteurs_uniq',
            field=models.IntegerField(default=0, help_text="Nombre d'emprunteurs distincts ayant emprunté ce livre."),
        ),
        migrations.AddField(
            model_name='book',
            name='nb_emprunts',
            field=models.IntegerField(default=0, help_text='Nombre total de prêts de ce livre.'),
        ),
        migrations.AddField(
            model_name='book',
            name='popularite',
            field=models.FloatField(default=0.0, help_text='Score de popularité globale brute.'),
        ),
        migrations.AddField(
            model_name='book',
            name='popularite_log',
            field=models.FloatField(default=0.0, help_text='log(1 + nb_emprunteurs_uniq) — Indice de popularité normalisé pour le NMF / TF-IDF.'),
        ),
        migrations.AddField(
            model_name='book',
            name='score_lecture_max',
            field=models.FloatField(default=0.0, help_text='Score de lecture maximum observé.'),
        ),
        migrations.AddField(
            model_name='book',
            name='score_lecture_moy',
            field=models.FloatField(default=0.0, help_text='Score de lecture moyen des emprunteurs.'),
        ),
        migrations.AddField(
            model_name='borrow',
            name='date_retour_effective',
            field=models.DateField(blank=True, help_text="Date réelle de retour physique de l'ouvrage.", null=True),
        ),
        migrations.AddField(
            model_name='borrow',
            name='date_retour_prevue',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date limite de retour du livre (date_sortie + 14 jours).'),
        ),
        migrations.AddField(
            model_name='borrow',
            name='date_sortie',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date à laquelle le livre quitte physiquement la bibliothèque.'),
        ),
        migrations.AddField(
            model_name='user',
            name='demande_adhesion',
            field=models.BooleanField(default=False, help_text="Indique si l'utilisateur a soumis une demande d'adhésion physique."),
        ),
        migrations.AlterField(
            model_name='book',
            name='annee',
            field=models.IntegerField(blank=True, help_text="Année d'édition ou de publication.", null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='auteur',
            field=models.CharField(blank=True, help_text="Nom complet de l'auteur.", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='categorie_age',
            field=models.CharField(choices=[('enfant', 'Enfant'), ('ado', 'Ado'), ('adulte', 'Adulte')], default='adulte', help_text="Tranche d'âge cible pour la lecture.", max_length=10),
        ),
        migrations.AlterField(
            model_name='book',
            name='codes_barres',
            field=models.TextField(blank=True, help_text='Codes barres de tous les exemplaires associés (séparés par des virgules).', null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='couverture_url',
            field=models.CharField(blank=True, help_text="URL de l'image de couverture.", max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='exemplaires',
            field=models.IntegerField(default=1, help_text="Nombre d'exemplaires physiques disponibles pour le prêt."),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, help_text='Genre principal (ex: Roman, Essai, Bande dessinée).', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='langue',
            field=models.CharField(default='fr', help_text="Code langue de l'ouvrage (fr par défaut).", max_length=10),
        ),
        migrations.AlterField(
            model_name='book',
            name='localisation',
            field=models.CharField(blank=True, help_text="Localisation précise de l'ouvrage dans les rayons.", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='mots_cles',
            field=models.TextField(blank=True, help_text='Mots-clés associés séparés par des virgules.', null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='nb_notes',
            field=models.IntegerField(default=0, help_text="Nombre d'avis de notation enregistrés."),
        ),
        migrations.AlterField(
            model_name='book',
            name='nb_pages',
            field=models.IntegerField(blank=True, help_text='Nombre total de pages du livre.', null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='note_moyenne',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Note moyenne calculée à partir des avis (0 à 5).', max_digits=3),
        ),
        migrations.AlterField(
            model_name='book',
            name='resume',
            field=models.TextField(blank=True, help_text="Résumé détaillé de l'œuvre.", null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='section',
            field=models.CharField(blank=True, help_text='Section physique de rangement (texte libre, ex: Roman, Sciences).', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='sous_genre',
            field=models.CharField(blank=True, help_text='Sous-genre optionnel pour classification plus fine.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='titre',
            field=models.CharField(help_text="Titre complet de l'ouvrage.", max_length=300),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='livre',
            field=models.ForeignKey(help_text='Livre emprunté.', on_delete=django.db.models.deletion.CASCADE, related_name='borrows', to='api.book'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='renouvele',
            field=models.BooleanField(default=False, help_text="Indique si l'emprunt a été prolongé/renouvelé."),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='statut',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('rendu', 'Rendu'), ('perdu', 'Perdu')], default='en_cours', help_text="Statut actuel de l'emprunt (en cours, rendu, perdu).", max_length=20),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='user',
            field=models.ForeignKey(help_text='Membre emprunteur.', on_delete=django.db.models.deletion.CASCADE, related_name='borrows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='content',
            field=models.TextField(help_text='Contenu du message.'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='role',
            field=models.CharField(choices=[('user', 'Utilisateur'), ('assistant', 'Assistant')], help_text='Auteur du message (user ou assistant).', max_length=10),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='session',
            field=models.ForeignKey(help_text='Session de chat associée.', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.chatsession'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='titre',
            field=models.CharField(default='Nouvelle conversation', help_text='Titre de la session de chat.', max_length=200),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='user',
            field=models.ForeignKey(help_text='Utilisateur propriétaire de la conversation.', on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clubcontactmessage',
            name='club',
            field=models.ForeignKey(help_text='Club destinataire.', on_delete=django.db.models.deletion.CASCADE, related_name='contact_messages', to='api.readingclub'),
        ),
        migrations.AlterField(
            model_name='clubcontactmessage',
            name='email',
            field=models.EmailField(help_text="Adresse email de l'expéditeur.", max_length=254),
        ),
        migrations.AlterField(
            model_name='clubcontactmessage',
            name='message',
            field=models.TextField(help_text='Contenu du message.'),
        ),
        migrations.AlterField(
            model_name='clubcontactmessage',
            name='nom',
            field=models.CharField(help_text="Nom complet fourni par l'expéditeur.", max_length=100),
        ),
        migrations.AlterField(
            model_name='clubcontactmessage',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Utilisateur connecté (si applicable).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='club',
            field=models.ForeignKey(blank=True, help_text='Club de lecture associé (optionnel).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.readingclub'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(help_text="Date de tenue de l'événement."),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(help_text="Description de l'événement et de son programme."),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(help_text='Lieu physique ou salon virtuel.', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='participant_count',
            field=models.IntegerField(default=0, help_text='Nombre total de participants enregistrés.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.CharField(help_text="Créneau horaire de l'événement (ex: 15h-17h).", max_length=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(help_text="Titre de l'événement.", max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='type_event',
            field=models.CharField(choices=[('club', 'Club'), ('conference', 'Conférence'), ('workshop', 'Atelier')], default='conference', help_text="Type d'événement.", max_length=20),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='duree_secondes',
            field=models.IntegerField(blank=True, help_text='Temps passé sur la page du livre.', null=True),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='livre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='api.book'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='livre_lu',
            field=models.BooleanField(default=False, help_text='Indique si le livre a été marqué comme lu.'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='notation',
            field=models.IntegerField(blank=True, help_text='Note éventuelle de 1 à 5.', null=True),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='position',
            field=models.IntegerField(blank=True, help_text='Position dans une liste de recommandations.', null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(blank=True, help_text="Corps complet de l'article.", null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(help_text="Date de publication de l'article."),
        ),
        migrations.AlterField(
            model_name='news',
            name='excerpt',
            field=models.TextField(help_text="Résumé court de l'article affiché sur la liste des actualités."),
        ),
        migrations.AlterField(
            model_name='news',
            name='featured',
            field=models.BooleanField(default=False, help_text="Indique si l'article est épinglé en vedette sur l'accueil."),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.CharField(blank=True, help_text="Lien vers l'image d'illustration.", max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(help_text="Titre de l'actualité.", max_length=200),
        ),
        migrations.AlterField(
            model_name='notification',
            name='emprunt',
            field=models.ForeignKey(blank=True, help_text='Emprunt concerné (si applicable).', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.borrow'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='livre',
            field=models.ForeignKey(blank=True, help_text='Livre concerné (si applicable).', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.book'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='lue',
            field=models.BooleanField(default=False, help_text="Indique si l'utilisateur a lu la notification."),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(help_text='Contenu textuel de la notification.'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type_notif',
            field=models.CharField(choices=[('rappel_retour', 'Rappel retour'), ('retard', 'Retard'), ('livre_disponible', 'Livre disponible'), ('demande_adhesion', 'Demande adhésion'), ('adhesion_confirmee', 'Adhésion confirmée'), ('inscription_evenement', 'Inscription événement')], help_text='Type de notification.', max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(help_text='Destinataire de la notification.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='participationevent',
            name='date_inscription',
            field=models.DateTimeField(auto_now_add=True, help_text="Date d'inscription à l'événement."),
        ),
        migrations.AlterField(
            model_name='participationevent',
            name='email',
            field=models.EmailField(help_text='Adresse email pour les informations et confirmations.', max_length=254),
        ),
        migrations.AlterField(
            model_name='participationevent',
            name='event',
            field=models.ForeignKey(help_text='Événement concerné.', on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='api.event'),
        ),
        migrations.AlterField(
            model_name='participationevent',
            name='motivations',
            field=models.TextField(blank=True, help_text='Motivations éventuelles renseignées par le participant.', null=True),
        ),
        migrations.AlterField(
            model_name='participationevent',
            name='nom_complet',
            field=models.CharField(help_text="Nom complet du participant saisi lors de l'inscription.", max_length=200),
        ),
        migrations.AlterField(
            model_name='participationevent',
            name='telephone',
            field=models.CharField(help_text='Numéro de téléphone de contact.', max_length=20),
        ),
        migrations.AlterField(
            model_name='participationevent',
            name='user',
            field=models.ForeignKey(help_text='Utilisateur participant.', on_delete=django.db.models.deletion.CASCADE, related_name='event_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='readingclub',
            name='description',
            field=models.TextField(help_text='Description des objectifs et thématiques du club.'),
        ),
        migrations.AlterField(
            model_name='readingclub',
            name='image',
            field=models.CharField(blank=True, help_text="URL de l'image représentative du club.", max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='readingclub',
            name='manager_email',
            field=models.CharField(blank=True, help_text='Email de contact du responsable.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='readingclub',
            name='manager_name',
            field=models.CharField(blank=True, help_text='Nom du bibliothécaire/animateur responsable.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='readingclub',
            name='manager_role',
            field=models.CharField(blank=True, help_text='Rôle du responsable (ex: Animateur principal).', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='readingclub',
            name='member_count',
            field=models.IntegerField(default=0, help_text='Nombre de membres adhérents au club.'),
        ),
        migrations.AlterField(
            model_name='readingclub',
            name='members',
            field=models.ManyToManyField(blank=True, help_text='Membres adhérents à ce club.', related_name='clubs_adherant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='readingclub',
            name='name',
            field=models.CharField(help_text='Nom unique du club de lecture.', max_length=200),
        ),
        migrations.AlterField(
            model_name='readingclub',
            name='target_audience',
            field=models.CharField(choices=[('children', 'Enfants'), ('teen', 'Adolescents'), ('adult', 'Adultes'), ('all', 'Tout public')], default='all', help_text='Public visé par le club de lecture.', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_reservation',
            field=models.DateTimeField(auto_now_add=True, help_text='Date et heure de soumission de la demande.'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='livre',
            field=models.ForeignKey(help_text='Livre réservé.', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='api.book'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('prete', 'Prête'), ('annulee', 'Annulée'), ('terminee', 'Terminée')], default='en_attente', help_text='Statut de la demande.', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(help_text='Membre réservataire.', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='commentaire',
            field=models.TextField(help_text='Commentaire écrit du lecteur.'),
        ),
        migrations.AlterField(
            model_name='review',
            name='livre',
            field=models.ForeignKey(help_text='Livre noté.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.book'),
        ),
        migrations.AlterField(
            model_name='review',
            name='note',
            field=models.IntegerField(help_text='Note attribuée de 1 à 5.'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(help_text="Auteur de l'avis.", on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sessionia',
            name='active',
            field=models.BooleanField(default=True, help_text='Indique si la session de recommandation est toujours en cours.'),
        ),
        migrations.AlterField(
            model_name='sessionia',
            name='humeur_detectee',
            field=models.CharField(choices=[('léger', 'Léger'), ('intense', 'Intense'), ('évasion', 'Évasion'), ('neutre', 'Neutre'), ('triste', 'Triste'), ('aventurier', 'Aventurier'), ('romantique', 'Romantique'), ('curieux', 'Curieux'), ('nostalgique', 'Nostalgique'), ('stressé', 'Stressé'), ('détendu', 'Détendu')], default='neutre', help_text='Humeur détectée par le chatbot.', max_length=20),
        ),
        migrations.AlterField(
            model_name='sessionia',
            name='livres_acceptes',
            field=models.JSONField(blank=True, help_text="Liste des livres suggérés et acceptés par l'utilisateur.", null=True),
        ),
        migrations.AlterField(
            model_name='sessionia',
            name='livres_rejetes',
            field=models.JSONField(blank=True, help_text="Liste des livres suggérés mais rejetés par l'utilisateur.", null=True),
        ),
        migrations.AlterField(
            model_name='sessionia',
            name='user',
            field=models.ForeignKey(help_text='Utilisateur lié à la session.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sessionia',
            name='vecteur_intention',
            field=models.JSONField(blank=True, help_text="Vecteur d'intention de lecture calculé.", null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, help_text='Lien ou URL de la photo de profil.', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text="Courte biographie rédigée par l'utilisateur.", null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='classe',
            field=models.CharField(blank=True, help_text="Classe spécifique de l'élève ou de l'étudiant.", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_inscription',
            field=models.DateTimeField(auto_now_add=True, help_text='Date et heure de création du compte sur la plateforme.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_naissance',
            field=models.DateField(blank=True, help_text="Date de naissance de l'utilisateur.", null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='favorites',
            field=models.JSONField(blank=True, default=list, help_text="Liste des identifiants des livres favoris de l'utilisateur."),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='user',
            name='genres_preferes',
            field=models.JSONField(blank=True, default=list, help_text='Genres littéraires favoris.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='intentions',
            field=models.JSONField(blank=True, default=list, help_text="Objectifs/intentions de lecture déclarés à l'inscription."),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Nom de famille'),
        ),
        migrations.AlterField(
            model_name='user',
            name='niveau_etude',
            field=models.CharField(blank=True, help_text="Niveau d'étude actuel (Primaire, Secondaire, Supérieur, etc.).", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pseudo',
            field=models.CharField(blank=True, help_text="Nom d'affichage public (pseudonyme).", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sous_genre_prefere',
            field=models.JSONField(blank=True, default=list, help_text='Sous-genres littéraires favoris.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(blank=True, help_text='Numéro de téléphone de contact (optionnel).', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='type_compte',
            field=models.CharField(choices=[('non_membre', 'Non-membre'), ('en_attente', 'En attente'), ('membre', 'Membre')], default='non_membre', help_text='Statut du compte : non-membre par défaut, puis membre après validation physique par le bibliothécaire.', max_length=20),
        ),
        migrations.DeleteModel(
            name='LabStation',
        ),
        migrations.DeleteModel(
            name='LabReservation',
        ),
    ]
