# Generated by Django 6.0.4 on 2026-05-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_labreservation_station_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='couverture_url',
            field=models.CharField(blank=True, default='https://www.cosmopolitan.fr/les-5-plus-beaux-livres-de-colleen-hoover-pour-decouvrir-la-new-romance,2120559.asp', help_text="URL de l'image de couverture.", max_length=300, null=True),
        ),
    ]
