# Generated by Django 6.0.4 on 2026-05-30 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_book_couverture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='type_action',
            field=models.CharField(choices=[('vue', 'Vue'), ('note', 'Note'), ('like', "J'aime"), ('chat_ia', 'Chat IA'), ('marquage', 'Marquage'), ('recommandation_impression', 'Impression recommandation'), ('recommandation_clic', 'Clic recommandation'), ('favori_ajout', 'Ajout favori'), ('favori_suppression', 'Suppression favori')]),
        ),
    ]
