# Generated by Django 6.0.4 on 2026-05-30 02:17

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_interaction_type_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='type_action',
            field=models.CharField(choices=[('vue', 'Vue'), ('note', 'Note'), ('like', "J'aime"), ('chat_ia', 'Chat IA'), ('marquage', 'Marquage'), ('recommandation_impression', 'Impression recommandation'), ('recommandation_clic', 'Clic recommandation'), ('favori_ajout', 'Ajout favori'), ('favori_suppression', 'Suppression favori')], max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_inscription',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date et heure de création du compte sur la plateforme.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=40, primary_key=True, serialize=False),
        ),
    ]
